name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}-${{ steps.get-date.outputs.date }}
        restore-keys: |
          ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}-

    - name: Build with Buildozer
      uses: ArtemSashko/buildozer-action@v1
      with:
        command: buildozer android debug
        buildozer_version: master

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Zo3rob-Supermarket-APK
        path: bin/*.apk
